/* insert school year test data */
insert into school_year (id, name, date_start, date_end) values (1, 'Depreault''s Snow Lichen', '1/31/2021', '7/8/2020');
insert into school_year (id, name, date_start, date_end) values (2, 'San Bernardino Mountain Monkeyflower', '12/18/2020', '7/10/2020');
insert into school_year (id, name, date_start, date_end) values (3, 'Dimeresia', '10/11/2020', '5/29/2020');

/* insert 60 users test data with student role */
insert into user (id, roles, password, firstname, lastname, phone, school_year_id) values (1, 'ROLE_STUDENT', 'OjbfYWmGZ', 'Joyann', 'Sauvain', '3521231534', 1);
insert into user (id, roles, password, firstname, lastname, phone, school_year_id) values (2, 'ROLE_STUDENT', 'Gek4pkbmBt4r', 'Cullan', 'Elliker', '9378676642', 2);
insert into user (id, roles, password, firstname, lastname, phone, school_year_id) values (3, 'ROLE_STUDENT', '6kdrCGc', 'Dulcea', 'Eake', '7426672080', 3);
insert into user (id, roles, password, firstname, lastname, phone, school_year_id) values (4, 'ROLE_STUDENT', 'UrSerCA68', 'Normand', 'Manklow', '6788288760', 4);
insert into user (id, roles, password, firstname, lastname, phone, school_year_id) values (5, 'ROLE_STUDENT', 'sPWV9Xuvhi', 'Jordanna', 'Tregiddo', '1266839467', 5);
insert into user (id, roles, password, firstname, lastname, phone, school_year_id) values (6, 'ROLE_STUDENT', 'E4Z7sF2H', 'Almire', 'Newstead', '7918476430', 6);
insert into user (id, roles, password, firstname, lastname, phone, school_year_id) values (7, 'ROLE_STUDENT', 'I0lBkweSJ', 'Aurea', 'Scherer', '4662914169', 7);
insert into user (id, roles, password, firstname, lastname, phone, school_year_id) values (8, 'ROLE_STUDENT', 'nuhECb0sAI', 'Nial', 'Grzesiak', '4482238739', 8);
insert into user (id, roles, password, firstname, lastname, phone, school_year_id) values (9, 'ROLE_STUDENT', 'qG4WLGlRBpw', 'Danya', 'Christin', '2162767378', 9);
insert into user (id, roles, password, firstname, lastname, phone, school_year_id) values (10, 'ROLE_STUDENT', 'G4cB7NWkUtRv', 'Odell', 'Scrimgeour', '5866242919', 10);
insert into user (id, roles, password, firstname, lastname, phone, school_year_id) values (11, 'ROLE_STUDENT', 'nvNnqhEQf', 'Simonette', 'Rotge', '3551286394', 11);
insert into user (id, roles, password, firstname, lastname, phone, school_year_id) values (12, 'ROLE_STUDENT', 'crLZCUkxqMlb', 'Tomi', 'Truckett', '7042823229', 12);
insert into user (id, roles, password, firstname, lastname, phone, school_year_id) values (13, 'ROLE_STUDENT', '7Gu0W6EZI', 'Dominique', 'Kalkhoven', '8118882064', 13);
insert into user (id, roles, password, firstname, lastname, phone, school_year_id) values (14, 'ROLE_STUDENT', 'IWUH0zprvdd', 'Betsy', 'MacColgan', '8153319950', 14);
insert into user (id, roles, password, firstname, lastname, phone, school_year_id) values (15, 'ROLE_STUDENT', 'wFUjAWLBEa', 'Jayson', 'Norman', '7855922018', 15);
insert into user (id, roles, password, firstname, lastname, phone, school_year_id) values (16, 'ROLE_STUDENT', 'yyw6LVu', 'Rois', 'Capel', '5299601687', 16);
insert into user (id, roles, password, firstname, lastname, phone, school_year_id) values (17, 'ROLE_STUDENT', '9AWEOGCB', 'Damian', 'Pre', '6861525284', 17);
insert into user (id, roles, password, firstname, lastname, phone, school_year_id) values (18, 'ROLE_STUDENT', 'MeIQftp', 'Rod', 'Chettle', '3587556785', 18);
insert into user (id, roles, password, firstname, lastname, phone, school_year_id) values (19, 'ROLE_STUDENT', 'FkIAiIg4M', 'Braden', 'Mazzeo', '8901747278', 19);
insert into user (id, roles, password, firstname, lastname, phone, school_year_id) values (20, 'ROLE_STUDENT', 'MoRPbWVZ', 'Hillary', 'Branwhite', '8331710353', 20);
insert into user (id, roles, password, firstname, lastname, phone, school_year_id) values (21, 'ROLE_STUDENT', 'o98mKLMDynz4', 'Jameson', 'Tumini', '4668210343', 21);
insert into user (id, roles, password, firstname, lastname, phone, school_year_id) values (22, 'ROLE_STUDENT', 'wKYBBtV8Ao', 'Rad', 'Lambshine', '3399176392', 22);
insert into user (id, roles, password, firstname, lastname, phone, school_year_id) values (23, 'ROLE_STUDENT', 'LSUvSMWpNehS', 'Brod', 'Andreutti', '8129226064', 23);
insert into user (id, roles, password, firstname, lastname, phone, school_year_id) values (24, 'ROLE_STUDENT', 'lofOwTL', 'Arlin', 'Cadore', '1803665131', 24);
insert into user (id, roles, password, firstname, lastname, phone, school_year_id) values (25, 'ROLE_STUDENT', '9L2qUPwG43ca', 'Ruby', 'Yeulet', '7424906126', 25);
insert into user (id, roles, password, firstname, lastname, phone, school_year_id) values (26, 'ROLE_STUDENT', '0k09msoVf', 'Liz', 'Sewley', '7379565924', 26);
insert into user (id, roles, password, firstname, lastname, phone, school_year_id) values (27, 'ROLE_STUDENT', '4RhLWM', 'Marlon', 'April', '5476215606', 27);
insert into user (id, roles, password, firstname, lastname, phone, school_year_id) values (28, 'ROLE_STUDENT', 'JrySFr', 'Elston', 'Fealey', '1852880905', 28);
insert into user (id, roles, password, firstname, lastname, phone, school_year_id) values (29, 'ROLE_STUDENT', 'Q0UBGcitaA', 'Liam', 'Cahillane', '4469616217', 29);
insert into user (id, roles, password, firstname, lastname, phone, school_year_id) values (30, 'ROLE_STUDENT', 'h0rn93mFKaQ', 'Carolee', 'Sherr', '4294144747', 30);
insert into user (id, roles, password, firstname, lastname, phone, school_year_id) values (31, 'ROLE_STUDENT', 'VwdO6cWR', 'Pammie', 'Suart', '1802295607', 31);
insert into user (id, roles, password, firstname, lastname, phone, school_year_id) values (32, 'ROLE_STUDENT', 'tDnXId', 'Kathye', 'Sheehy', '9056595579', 32);
insert into user (id, roles, password, firstname, lastname, phone, school_year_id) values (33, 'ROLE_STUDENT', 'EeRIVTzit', 'Saul', 'Vedeneev', '3737669105', 33);
insert into user (id, roles, password, firstname, lastname, phone, school_year_id) values (34, 'ROLE_STUDENT', 'CWocgkKv', 'Eleanore', 'Claxton', '4956525275', 34);
insert into user (id, roles, password, firstname, lastname, phone, school_year_id) values (35, 'ROLE_STUDENT', 'nibn27T2', 'Cointon', 'Deschlein', '4557462910', 35);
insert into user (id, roles, password, firstname, lastname, phone, school_year_id) values (36, 'ROLE_STUDENT', 'YqGou3qZbvH', 'Anjela', 'Badsey', '1269956731', 36);
insert into user (id, roles, password, firstname, lastname, phone, school_year_id) values (37, 'ROLE_STUDENT', 'h7roslW6CxiU', 'Norbie', 'Eastham', '8927512896', 37);
insert into user (id, roles, password, firstname, lastname, phone, school_year_id) values (38, 'ROLE_STUDENT', 'FhyWB8pd', 'Carmina', 'Bishell', '6447390447', 38);
insert into user (id, roles, password, firstname, lastname, phone, school_year_id) values (39, 'ROLE_STUDENT', 'DgNcGCGCWQl', 'Gordy', 'Redier', '2047635406', 39);
insert into user (id, roles, password, firstname, lastname, phone, school_year_id) values (40, 'ROLE_STUDENT', 'iLe7RJWu', 'Olivette', 'Bothie', '6211807506', 40);
insert into user (id, roles, password, firstname, lastname, phone, school_year_id) values (41, 'ROLE_STUDENT', 'R9HkyzX', 'Lazare', 'Lethbury', '5195743333', 41);
insert into user (id, roles, password, firstname, lastname, phone, school_year_id) values (42, 'ROLE_STUDENT', 'm3gCyFUe', 'Gweneth', 'MacAdam', '5842534037', 42);
insert into user (id, roles, password, firstname, lastname, phone, school_year_id) values (43, 'ROLE_STUDENT', 'fcK8vUbp', 'Crichton', 'Budgett', '9045451911', 43);
insert into user (id, roles, password, firstname, lastname, phone, school_year_id) values (44, 'ROLE_STUDENT', 'VYDsHFSc', 'Angelo', 'Chessel', '8601338210', 44);
insert into user (id, roles, password, firstname, lastname, phone, school_year_id) values (45, 'ROLE_STUDENT', 'Yy0tQRNflgeq', 'Leroy', 'Mayze', '7647957984', 45);
insert into user (id, roles, password, firstname, lastname, phone, school_year_id) values (46, 'ROLE_STUDENT', 'gpudCa8yPd2', 'Ariella', 'Paulus', '7451810898', 46);
insert into user (id, roles, password, firstname, lastname, phone, school_year_id) values (47, 'ROLE_STUDENT', '9Vc6sDPB4s', 'Nicola', 'Liston', '6473576696', 47);
insert into user (id, roles, password, firstname, lastname, phone, school_year_id) values (48, 'ROLE_STUDENT', '5A4r3e', 'Tallia', 'Tumbridge', '1243192799', 48);
insert into user (id, roles, password, firstname, lastname, phone, school_year_id) values (49, 'ROLE_STUDENT', 'Zv89Jp', 'Herby', 'Chue', '7958753723', 49);
insert into user (id, roles, password, firstname, lastname, phone, school_year_id) values (50, 'ROLE_STUDENT', 'Wxpj382sDp8S', 'Wanda', 'Le Fevre', '3332418222', 50);
insert into user (id, roles, password, firstname, lastname, phone, school_year_id) values (51, 'ROLE_STUDENT', '5h7m9L', 'Fannie', 'Wetton', '3956772092', 51);
insert into user (id, roles, password, firstname, lastname, phone, school_year_id) values (52, 'ROLE_STUDENT', 'lg4Az0U', 'Van', 'Muzzullo', '5754605332', 52);
insert into user (id, roles, password, firstname, lastname, phone, school_year_id) values (53, 'ROLE_STUDENT', 'tVyBKpH', 'Cordell', 'Widmore', '9017179137', 53);
insert into user (id, roles, password, firstname, lastname, phone, school_year_id) values (54, 'ROLE_STUDENT', 'RPE1s8uaLvRy', 'Magdalena', 'Hamby', '5767400916', 54);
insert into user (id, roles, password, firstname, lastname, phone, school_year_id) values (55, 'ROLE_STUDENT', 'Vxjly0', 'Stanford', 'Millgate', '5187822774', 55);
insert into user (id, roles, password, firstname, lastname, phone, school_year_id) values (56, 'ROLE_STUDENT', 'nYjxC4ogQ', 'Lydon', 'Renehan', '4655732136', 56);
insert into user (id, roles, password, firstname, lastname, phone, school_year_id) values (57, 'ROLE_STUDENT', 'IAPZFK', 'Shawn', 'Bellhanger', '7123685573', 57);
insert into user (id, roles, password, firstname, lastname, phone, school_year_id) values (58, 'ROLE_STUDENT', '8gGzIN', 'Margie', 'Dalby', '7251072494', 58);
insert into user (id, roles, password, firstname, lastname, phone, school_year_id) values (59, 'ROLE_STUDENT', 'qZUOLENtsvb', 'Vale', 'Malsher', '6562779216', 59);
insert into user (id, roles, password, firstname, lastname, phone, school_year_id) values (60, 'ROLE_STUDENT', 'HzCuUl', 'Randolph', 'Kearsley', '1611964114', 60);

/* insert 5 users test data with teacher role */
insert into user (id, roles, password, firstname, lastname, phone, school_year_id) values (1, 'ROLE_TEACHER', 'VcUeq6Zqr', 'Ardyth', 'Jandl', '9864686961', 1);
insert into user (id, roles, password, firstname, lastname, phone, school_year_id) values (2, 'ROLE_TEACHER', 'drmElDkpH', 'Merrili', 'Geoghegan', '5506527848', 2);
insert into user (id, roles, password, firstname, lastname, phone, school_year_id) values (3, 'ROLE_TEACHER', 'cOq2LKh1ug', 'Maryanna', 'Alyutin', '8458157279', 3);
insert into user (id, roles, password, firstname, lastname, phone, school_year_id) values (4, 'ROLE_TEACHER', 'erIBPF9', 'Jayme', 'Fine', '3605858859', 4);
insert into user (id, roles, password, firstname, lastname, phone, school_year_id) values (5, 'ROLE_TEACHER', 'ubv53wfbh', 'Lovell', 'de Guerre', '5799050492', 5);

/* insert 15 users test data with customer role */
insert into user (id, roles, password, firstname, lastname, phone, school_year_id) values (1, 'ROLE_CLIENT', 'uzq7t6', 'Genna', 'Owenson', '5432844570', 1);
insert into user (id, roles, password, firstname, lastname, phone, school_year_id) values (2, 'ROLE_CLIENT', 'srDdhwec9y5N', 'Fionna', 'Swinglehurst', '3162823602', 2);
insert into user (id, roles, password, firstname, lastname, phone, school_year_id) values (3, 'ROLE_CLIENT', 'p45G5Fq', 'Ransom', 'Woffenden', '9913392606', 3);
insert into user (id, roles, password, firstname, lastname, phone, school_year_id) values (4, 'ROLE_CLIENT', '5RnHsQW', 'Hynda', 'O''Carrol', '8268420947', 4);
insert into user (id, roles, password, firstname, lastname, phone, school_year_id) values (5, 'ROLE_CLIENT', 'SxeZCAMF', 'Beverlie', 'Findlay', '5128317887', 5);
insert into user (id, roles, password, firstname, lastname, phone, school_year_id) values (6, 'ROLE_CLIENT', 'JcMQXN', 'Craggie', 'Isacoff', '4197161158', 6);
insert into user (id, roles, password, firstname, lastname, phone, school_year_id) values (7, 'ROLE_CLIENT', 'djXlySTApS', 'Klemens', 'Vanetti', '7254224452', 7);
insert into user (id, roles, password, firstname, lastname, phone, school_year_id) values (8, 'ROLE_CLIENT', 'eirP3IiIOsH', 'Link', 'Davage', '7591352733', 8);
insert into user (id, roles, password, firstname, lastname, phone, school_year_id) values (9, 'ROLE_CLIENT', 'cR71ULuc6', 'Shurwood', 'Weeks', '9416337001', 9);
insert into user (id, roles, password, firstname, lastname, phone, school_year_id) values (10, 'ROLE_CLIENT', 'Pi21ZaC3G', 'Joan', 'Barhims', '9381743273', 10);
insert into user (id, roles, password, firstname, lastname, phone, school_year_id) values (11, 'ROLE_CLIENT', 'QEPExBxGXCl', 'Gilburt', 'Howells', '4349482653', 11);
insert into user (id, roles, password, firstname, lastname, phone, school_year_id) values (12, 'ROLE_CLIENT', 'Jbqx4zVS7Wq', 'Leslie', 'Hacun', '3258667028', 12);
insert into user (id, roles, password, firstname, lastname, phone, school_year_id) values (13, 'ROLE_CLIENT', 'xOtla2qQAk9T', 'Marlo', 'Riden', '7171342889', 13);
insert into user (id, roles, password, firstname, lastname, phone, school_year_id) values (14, 'ROLE_CLIENT', 'A8guCn1', 'Erhart', 'Tompion', '4525231441', 14);
insert into user (id, roles, password, firstname, lastname, phone, school_year_id) values (15, 'ROLE_CLIENT', 'nUeFNOWvFJBR', 'Arthur', 'Elwood', '6451811071', 15);

/* insert 20 projects test data */
insert into project (id, name, description) values (1, 'Sesbania sericea (Willd.) Link', 'Revision of Drainage Device in Neck, External Approach');
insert into project (id, name, description) values (2, 'Cirsium drummondii Torr. & A. Gray', 'Supplement R Low Lobe Bronc with Nonaut Sub, Open Approach');
insert into project (id, name, description) values (3, 'Allowissadula holosericea (Scheele) D.M. Bates', 'Reposition Descending Colon, Endo');
insert into project (id, name, description) values (4, 'Serjania Mill.', 'Drainage of Right Hepatic Duct, Percutaneous Approach');
insert into project (id, name, description) values (5, 'Cyperus neokunthianus Kük.', 'Bypass L Atrium to R Pulm Art with Zooplastic, Open Approach');
insert into project (id, name, description) values (6, 'Lysimachia L.', 'Bypass L Com Iliac Art to R Femor A, Perc Endo Approach');
insert into project (id, name, description) values (7, 'Aruncus dioicus (Walter) Fernald var. vulgaris (Maxim.) H. Hara', 'Replacement of L Acetabulum with Nonaut Sub, Perc Approach');
insert into project (id, name, description) values (8, 'Streptanthus barbiger Greene', 'Reposition Left External Carotid Artery, Open Approach');
insert into project (id, name, description) values (9, 'Croton elliottii Chapm.', 'Motor Function Treatment of Neuro Up Back/UE using Oth Equip');
insert into project (id, name, description) values (10, 'Lathyrus graminifolius (S. Watson) T.G. White', 'Supplement R Index Finger w Nonaut Sub, Perc Endo');
insert into project (id, name, description) values (11, 'Carex serpenticola P. Zika', 'Supplement Right Orbit with Nonaut Sub, Perc Approach');
insert into project (id, name, description) values (12, 'Argythamnia californica Brandegee', 'Excision of Right Temporal Bone, Perc Approach, Diagn');
insert into project (id, name, description) values (13, 'Jeffersonia diphylla (L.) Pers.', 'Supplement Aort Valve fr Trunc Vlv w Zooplastic, Open');
insert into project (id, name, description) values (14, 'Eragrostis mauiensis Hitchc.', 'Dilate L Temporal Art, Bifurc, w 4+ Intralum Dev, Perc Endo');
insert into project (id, name, description) values (15, 'Phyllostachys Siebold & Zucc.', 'Alteration of Head with Autol Sub, Perc Endo Approach');
insert into project (id, name, description) values (16, 'Pleuropogon refractus (A. Gray) Benth. ex Vasey', 'Revision of Synthetic Substitute in Bladder, Open Approach');
insert into project (id, name, description) values (17, 'Purshia DC. ex Poir.', 'Reattachment of Lung Lingula, Open Approach');
insert into project (id, name, description) values (18, 'Primula tschuktschorum Kjellm.', 'Detachment at Right Hand, Partial 2nd Ray, Open Approach');
insert into project (id, name, description) values (19, 'Micarea peliocarpa (Anzi) Coppins & R. Sant.', 'Supplement Upper Back with Nonaut Sub, Perc Endo Approach');
insert into project (id, name, description) values (20, 'Plagiobothrys canescens Benth. var. canescens', 'Drainage of Left Upper Leg Skin, External Approach, Diagn');
